import pandas as pd

print("=" * 60)
print("❤️  HEART — FRAMINGHAM DATASET")
print("=" * 60)
df = pd.read_csv('datasets/heart/framingham.csv')
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Missing: {df.isnull().sum().sum()}")
print(f"Target distribution: {df['TenYearCHD'].value_counts().to_dict()}")
print(f"\nFirst 2 rows:\n{df.head(2)}")

print("\n" + "=" * 60)
print("🩸  DIABETES — NEW DATASET")
print("=" * 60)
df = pd.read_csv('datasets/diabetes/diabetes_prediction_dataset.csv')
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Missing: {df.isnull().sum().sum()}")
print(f"Target distribution: {df['diabetes'].value_counts().to_dict()}")
print(f"\nFirst 2 rows:\n{df.head(2)}")

print("\n" + "=" * 60)
print("🫀  LIVER — NEW DATASET")
print("=" * 60)
df = pd.read_csv('datasets/liver/liver_LPD_train.csv',
                 encoding='latin1')
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Missing: {df.isnull().sum().sum()}")
print(f"\nFirst 2 rows:\n{df.head(2)}")