import pandas as pd

print("=" * 60)
print("❤️  HEART DISEASE DATASET")
print("=" * 60)
df_heart = pd.read_csv('datasets/heart/heart.csv', sep=';')
print(f"Shape: {df_heart.shape}")
print(f"\nMissing Values:\n{df_heart.isnull().sum()}")
print(f"\nData Types:\n{df_heart.dtypes}")
print(f"\nFirst 3 rows:\n{df_heart.head(3)}")

print("\n" + "=" * 60)
print("🩸  DIABETES DATASET")
print("=" * 60)
df_diabetes = pd.read_csv('datasets/diabetes/diabetes.csv')
print(f"Shape: {df_diabetes.shape}")
print(f"\nMissing Values:\n{df_diabetes.isnull().sum()}")
print(f"\nData Types:\n{df_diabetes.dtypes}")
print(f"\nFirst 3 rows:\n{df_diabetes.head(3)}")

print("\n" + "=" * 60)
print("🫀  LIVER DISEASE DATASET")
print("=" * 60)
df_liver = pd.read_csv('datasets/liver/liver.csv', encoding='latin1')
print(f"Shape: {df_liver.shape}")
print(f"\nMissing Values:\n{df_liver.isnull().sum()}")
print(f"\nData Types:\n{df_liver.dtypes}")
print(f"\nFirst 3 rows:\n{df_liver.head(3)}")

print("\n" + "=" * 60)
print("🫘  KIDNEY DISEASE DATASET")
print("=" * 60)
df_kidney = pd.read_csv('datasets/kidney/kidney.csv')
print(f"Shape: {df_kidney.shape}")
print(f"\nMissing Values:\n{df_kidney.isnull().sum()}")
print(f"\nData Types:\n{df_kidney.dtypes}")
print(f"\nFirst 3 rows:\n{df_kidney.head(3)}")

print("\n" + "=" * 60)
print("🫘  KIDNEY DISEASE DATASET")
print("=" * 60)
df_kidney = pd.read_csv('datasets/kidney/kidney.csv')
print(f"Shape: {df_kidney.shape}")
print(f"\nMissing Values:\n{df_kidney.isnull().sum()}")
print(f"\nData Types:\n{df_kidney.dtypes}")
print(f"\nFirst 3 rows:\n{df_kidney.head(3)}")